apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: bebemenina.com.br
  dnsNames:
    - bebemenina.com.br
    - www.bebemenina.com.br
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - bebemenina.com.br
          - www.bebemenina.com.br